// Package sandbox confines what files a server process can see.
//
// This is the third and last piece of isolation that a container would give
// for free. internal/serveruser separates servers by unix identity and
// internal/netiso separates them on the network; both are defeated the moment
// a file is left world-readable, which on a machine an operator also logs into
// happens constantly.
//
// macOS has a kernel sandbox, the one that confines App Store applications,
// reachable through sandbox-exec(1). It applies a policy to a process and
// every child it spawns, and it is enforced in the kernel independently of
// file permissions, so it holds even when the unix bits do not.
//
// # What this is not
//
// It is not a mount namespace. A confined server still sees the host's real
// paths and still shares its PID space, so it can see that other processes
// exist. What it cannot do is read their files.
//
// The generated policy is deny-by-exception rather than deny-by-default. A
// deny-by-default profile for a JVM plus arbitrary plugins would need an
// allowance for every JDK, native library and temporary directory in use, and
// would break the first time a plugin touched something unforeseen. Naming
// what must stay secret is less thorough but is a control that keeps working,
// which matters more than one that is airtight until it is switched off. The
// consequence, stated plainly because it decides whether this is worth
// enabling: a confined server can still read ordinary world-readable files
// elsewhere on the machine. What it cannot read is anything named here.
package sandbox

import (
	"fmt"
	"path/filepath"
	"strings"

	"emperror.dev/errors"
)

// Profile describes the confinement for one server.
type Profile struct {
	// ServerDir is the server's own data directory, the one place it keeps
	// full read and write access to.
	ServerDir string

	// WingsRoot is Wings' root directory. Its contents are denied, which
	// covers both config.yml with the node token and every other server's
	// files under volumes/.
	WingsRoot string

	// Deny lists additional paths to withhold. Operators use this for secrets
	// that live outside Wings' directory, such as ssh keys.
	Deny []string

	// HideProcesses stops a server seeing any process but its own.
	//
	// This is the closest thing macOS has to a PID namespace. It does not
	// renumber pids, so it is not one: what it removes is the ability to
	// enumerate or inspect anything else running on the machine. Sending
	// signals to another server is already refused by the per-server accounts,
	// so together they cover what a PID namespace would.
	//
	// It is off by default because it is absolute: ps, top and pgrep stop
	// working inside the server entirely, including on itself, since they have
	// to enumerate before they can filter. A JVM is unaffected, but a startup
	// script that shells out to ps to check whether something is running will
	// break.
	HideProcesses bool
}

// Generate renders a sandbox profile in SBPL, the Scheme-like language
// sandbox-exec reads.
//
// Rule order is significant: later rules override earlier ones, so each
// section below narrows or reopens what the one before it decided.
func Generate(p Profile) (string, error) {
	if p.ServerDir == "" {
		return "", errors.New("sandbox: a server directory is required")
	}
	if !filepath.IsAbs(p.ServerDir) {
		return "", errors.Errorf("sandbox: server directory must be absolute, got %q", p.ServerDir)
	}
	if p.WingsRoot != "" && !filepath.IsAbs(p.WingsRoot) {
		return "", errors.Errorf("sandbox: wings root must be absolute, got %q", p.WingsRoot)
	}

	// Paths must be resolved before they reach the kernel. macOS firmlinks
	// /var, /tmp and /etc onto /private, and the sandbox matches on the
	// resolved path, so a rule written against /var/... silently matches
	// nothing at all. That failure mode is a profile that loads cleanly and
	// confines nothing, which is the worst possible way for this to break.
	serverDir := resolve(p.ServerDir)
	root := resolve(p.WingsRoot)

	// A profile that denied the server its own directory would be generated
	// happily and then fail at boot with an error naming neither the sandbox
	// nor the reason, so refuse it here instead.
	if root != "." && root != "" && !within(serverDir, root) {
		return "", errors.Errorf("sandbox: server directory %q is not inside the wings root %q", serverDir, root)
	}

	var b strings.Builder
	b.WriteString("(version 1)\n")
	b.WriteString("; Generated by wings. Do not edit; regenerated on every server boot.\n")
	b.WriteString("(allow default)\n\n")

	if root != "." && root != "" {
		b.WriteString("; Wings' own directory: config.yml holds this node's token, and\n")
		b.WriteString("; volumes/ holds every other server's files.\n")
		fmt.Fprintf(&b, "(deny file-read* file-write* %s)\n\n", subpath(root))

		b.WriteString("; Metadata stays readable so the path can still be walked. Without this a\n")
		b.WriteString("; server cannot chdir into its own directory, because reaching it means\n")
		b.WriteString("; stat'ing the denied parents on the way down. This leaks names and sizes,\n")
		b.WriteString("; not file contents.\n")
		fmt.Fprintf(&b, "(allow file-read-metadata %s)\n\n", subpath(root))
	}

	for _, d := range p.Deny {
		if !filepath.IsAbs(d) {
			return "", errors.Errorf("sandbox: deny path must be absolute, got %q", d)
		}
		// Denying an ancestor of the server's own directory would be undone by
		// the allow below, so the operator's intent could not be honoured.
		if within(serverDir, resolve(d)) {
			return "", errors.Errorf("sandbox: deny path %q contains the server's own directory, which would have no effect", d)
		}
		fmt.Fprintf(&b, "(deny file-read* file-write* %s)\n", subpath(resolve(d)))
	}
	if len(p.Deny) > 0 {
		b.WriteString("\n")
	}

	b.WriteString("; The server's own data directory, carved back out. This comes last so it\n")
	b.WriteString("; wins over the denials above.\n")
	fmt.Fprintf(&b, "(allow file-read* file-write* %s)\n", subpath(serverDir))

	if p.HideProcesses {
		b.WriteString("\n; Everything else on the machine becomes invisible. Signals to other\n")
		b.WriteString("; servers are already refused by their separate accounts, so this covers\n")
		b.WriteString("; the remaining half of what a PID namespace would give.\n")
		b.WriteString("(deny process-info* (target others))\n")
	}

	return b.String(), nil
}

// resolve cleans a path and follows any symlinks and firmlinks in it.
//
// A path that does not exist is returned cleaned but unresolved. That is the
// right answer for a deny entry naming a directory the operator has not
// created, and it keeps the rule harmless: a path that cannot be walked cannot
// be read through either.
func resolve(p string) string {
	if p == "" {
		return ""
	}
	cleaned := filepath.Clean(p)
	real, err := filepath.EvalSymlinks(cleaned)
	if err != nil {
		return cleaned
	}
	return real
}

// within reports whether path is inside base.
func within(path, base string) bool {
	rel, err := filepath.Rel(base, path)
	if err != nil {
		return false
	}
	return rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

// subpath renders an SBPL subpath filter.
//
// SBPL string literals are Scheme-like, so a quote or backslash in a path
// would otherwise end the literal early and change the meaning of the rule,
// which for a policy file is a way to grant access rather than merely to break
// parsing.
func subpath(p string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `(subpath "` + r.Replace(p) + `")`
}
